package com.smparkworld.discord.common.base

enum class StringCode {
    NAME,
    IGNORED_USER,
    WILDCARD,
    SELECTED_MAP,
    IGNORED_MAP,
    STATUS,

    MUSIC_KEYWORD,
    MUSIC_KEYWORD_DESC,

    TARGET_USER,
    TARGET_USER_DESC,

    IGNORE1,
    IGNORE2,
    IGNORE3,
    IGNORE4,
    IGNORE5,
    IGNORE6,
    IGNORE7,
    IGNORE8,

    IGNORE_USER_DESC,
    IGNORE_MAP_DESC,

    ABSENT_COMMAND_AUTHOR,
    UNKNOWN_EXCEPTION,

    /* 꿀벌 봇 관련 START */
    BEE_CMD,
    BEE_CMD_DESC,

    BEE_CMD_HELP,
    BEE_CMD_HELP_DESC,

    BEE_CMD_FORCE_MOVE_USER,
    BEE_CMD_FORCE_MOVE_USER_DESC,
    BEE_CMD_FORCE_MOVE_USER_TARGET_USER_EMPTY,
    BEE_CMD_FORCE_MOVE_USER_TARGET_USER_HAS_NOT_CHANNEL,
    BEE_CMD_FORCE_MOVE_USER_TARGET_USER_IN_LIMIT,
    BEE_CMD_FORCE_MOVE_USER_TARGET_USER_SUCCESS,

    BEE_CMD_MUSIC_PLAY_BY_SEARCH,
    BEE_CMD_MUSIC_PLAY_BY_SEARCH_DESC,
    BEE_CMD_MUSIC_PLAY_INPUT_EMPTY,
    BEE_CMD_MUSIC_PLAY_NOT_FOUND,

    BEE_CMD_MUSIC_PLAY_LEAVE,
    BEE_CMD_MUSIC_PLAY_LEAVE_DESC,
    BEE_CMD_MUSIC_PLAY_LEAVE_MSG_1,
    BEE_CMD_MUSIC_PLAY_LEAVE_MSG_2,
    BEE_CMD_MUSIC_PLAY_LEAVE_MSG_3,

    BEE_CMD_MUSIC_PLAY_TITLE,
    BEE_CMD_MUSIC_PLAY_HELP_1_TITLE,
    BEE_CMD_MUSIC_PLAY_HELP_1_DESC,
    BEE_CMD_MUSIC_PLAY_HELP_2_TITLE,
    BEE_CMD_MUSIC_PLAY_HELP_2_DESC,
    BEE_CMD_MUSIC_PLAY_DESC_EMPTY,
    BEE_CMD_MUSIC_PLAY_CURRENT_TITLE,
    BEE_CMD_MUSIC_PLAY_CURRENT_TITLE_EXCEPTION,
    BEE_CMD_MUSIC_PLAY_PLAYLIST,

    BEE_CMD_HELP_QUESTION,
    BEE_CMD_HELP_QUESTION_DESC,

    BEE_CMD_HELP_FOR_BEE,
    BEE_CMD_HELP_FOR_BEE_DESC,

    BEE_CMD_HELP_FOR_VAL,
    BEE_CMD_HELP_FOR_VAL_DESC,

    BEE_CMD_HELP_FOR_BEE_HELP_EXAMPLE,
    BEE_CMD_HELP_FOR_BEE_FORCE_MOVE_USER_EXAMPLE,
    BEE_CMD_HELP_FOR_BEE_MUSIC_PLAY_BY_SEARCH_EXAMPLE,
    BEE_CMD_HELP_FOR_BEE_MUSIC_PLAY_LEAVE_EXAMPLE,
    BEE_CMD_HELP_FOR_VAL_RANDOM_PICK_EXAMPLE,
    BEE_CMD_HELP_FOR_VAL_RANDOM_PICK_HARD_EXAMPLE,
    BEE_CMD_HELP_FOR_VAL_RANDOM_MAP_EXAMPLE,
    BEE_CMD_HELP_FOR_VAL_TEAM_EXAMPLE,
    /* 꿀벌 봇 관련 END */

    /* 발로란트 봇 관련 START */
    VAL_CMD,
    VAL_CMD_DESC,

    VAL_CMD_RANDOM_PICK,
    VAL_CMD_RANDOM_PICK_DESC,

    VAL_CMD_RANDOM_PICK_HARD,
    VAL_CMD_RANDOM_PICK_HARD_DESC,

    VAL_CMD_RANDOM_MAP,
    VAL_CMD_RANDOM_MAP_DESC,

    VAL_CMD_TEAM,
    VAL_CMD_TEAM_DESC,

    VAL_AGENT,
    VAL_AGENT_TYPE,

    VAL_RANDOM_PICK_CANDIDATE_NEED_TO_MORE,
    VAL_RANDOM_PICK_CANDIDATE_TOO_MUCH,

    VAL_RANDOM_PICK_TITLE,
    VAL_RANDOM_PICK_DESCRIPTION,

    VAL_RANDOM_PICK_HARD_TITLE,
    VAL_RANDOM_PICK_HARD_DESCRIPTION,

    VAL_RANDOM_MAP_TITLE,
    VAL_RANDOM_MAP_DESCRIPTION,
    VAL_RANDOM_MAP_TOO_MUCH_IGNORED,

    VAL_TEAM_CANDIDATE_NEED_TO_MORE,
    VAL_TEAM_CANDIDATE_TOO_MUCH,

    VAL_TEAM_AUDIO_CHANNEL_NAME,
    VAL_TEAM_AUDIO_CHANNEL_NAME_A,
    VAL_TEAM_AUDIO_CHANNEL_NAME_B,

    VAL_TEAM_RESULT_TITLE,
    VAL_TEAM_RESULT_DESC,
    VAL_TEAM_RESULT_GROUP_A,
    VAL_TEAM_RESULT_GROUP_B,

    VAL_TEAM_FINISH_TITLE,
    VAL_TEAM_FINISH_DESC,
    /* 발로란트 봇 관련 END */
    ;

    val key: String
        get() = this.name.lowercase()
}